name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web
  publish:
    name: Plz Work(AKA publish)
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: docker build -t obihen/dotnettemplate:hop .
    - name: docker Login
      run: echo ${{ secrets.DOCKERPASSWORD }} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
    - name: Docker Push
      run: docker push obihen/dotnettemplate:hop
  heroku:
    runs-on: ubuntu-latest
    needs: [build,publish]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKUTOKEN}}
          heroku_app_name: "thanos-cow" #Must be unique in Heroku
          heroku_email: "joshua.knights@iris.co.uk"
          usedocker: true