name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: build       # Name of step
      run: dotnet build
    - name: test
      run: dotnet test

  typescript:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install npm@latest

    - name: ts build
      run: npm run build
      working-directory: DotnetTemplate.Web
    - name: ts lint
      run: npm run lint
      working-directory: DotnetTemplate.Web
    - name: ts test
      run: npm t
      working-directory: DotnetTemplate.Web
  publish:
    name: Plz Work(AKA publish)
    needs: [build,typescript]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install npm@latest

    - name: docker build
      run: docker build -t obihen/dotnettemplate:hop .
    
    - name: Docker Push
      run: docker push obihen/dotnettemplate:hop hop